
//CIRCLE GENERATED BY STANDARD DEVIATION
class FairwayDispersionEllipse extends React.Component {
    constructor(props) {
        super(props);
        
        this.state = {
            resultX : -1, 
            resultY: 0.0,
            avgDist: 0.0
        };
    }
     
    render() {    
        
        
        //CALCULATING STANDARD DEVIATION
        var resultX = 0.0; 
        var resultY = 0.0; 
        var avgShotDist = 0.0; 
        var sumShotDist = 0.0; 
        var avgCenterLineDist = 0.0;  //avg center line dist
        var sumCenterLineDist = 0.0;  //sum center line dist
        var N = this.props.data.length; 
        var resX = 0.0; 
        var resY = 0.0;
        
        //calculate arithmetic mean of SHOT_DIST
        for(var i = 0; i < N; i++){
            
            sumShotDist += this.props.data[i].SHOT_DIST;
            
            sumCenterLineDist += this.props.data[i].CENTER_LINE_DIST;
            
        }
        
        //average of SHOT_DIST
        avgShotDist = parseFloat(sumShotDist / N);
        
        //average of CENTER_LINE_DIST
        avgCenterLineDist = parseFloat(sumCenterLineDist / N);
        
        for(var i = 0; i < N; i++){
            
            resX += Math.pow((this.props.data[i].CENTER_LINE_DIST - avgCenterLineDist), 2);
            
            resY += Math.pow((this.props.data[i].SHOT_DIST - avgShotDist), 2);
            
        }
        
        //Std Deviation of CENTER_LINE_DIST    
        resultX = parseFloat(Math.sqrt(resX / N).toFixed(4));   
        
        //Std Deviation of SHOT_DIST 
        resultY = parseFloat(Math.sqrt(resY / N).toFixed(4));   
                
        var ellipsePosX = this.props.x(this.props.avgDisp);
        var ellipsePosY = this.props.y(avgShotDist);
        var ellipseRadiusX = this.props.x(this.props.avgDisp + resultX);
        ellipseRadiusX = ellipseRadiusX - ellipsePosX;
        var ellipseRadiusY = this.props.y(avgShotDist - resultY);
        ellipseRadiusY = ellipseRadiusY - ellipsePosY;
        
        return (
            <g>
                <ellipse cx={ellipsePosX} cy={ellipsePosY} rx={ellipseRadiusX} ry={ellipseRadiusY} className="eclipse" />
            </g>
        );
    }
}

window.FairwayDispersionEllipse = FairwayDispersionEllipse;
